apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: busybox
    app.kubernetes.io/component: cache
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command: 
          - sleep
        args:
          - '300'
