apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: server
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - image: docker.pkg.github.com/phoban01/gitops-demo/nginx:latest
        name: nginx
