apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
  name: redis
  namespace: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - image: redis
        name: redis
