name: Docker Image CI
on: 
  push:
    branches:
      - staging
    paths:
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/phoban01/gitops-demo/nginx:${GITHUB_SHA:0:8}
    - name: Push the Docker image
      run: |
        echo "$GH_TOKEN" | docker login docker.pkg.github.com -u "$GH_USER" --password-stdin
        docker push docker.pkg.github.com/phoban01/gitops-demo/nginx:${GITHUB_SHA:0:8}
      env:
        GH_USER: ${{ secrets.GH_USER }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Update nginx deployment
      run: sed -i s/nginx:latest/:${GITHUB_SHA:0:8}/ kubernetes/deploy/nginx.yaml
    - name: Create PR
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        source_branch: "staging"
        destination_branch: "master"
        pr_title: "Update nginx image"
        pr_label: "auto-pr"
