name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $docker tag IMAGE_ID phoban01/gitops-demo/nginx:$(date +%s)
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/phoban01/gitops-demophoban01/gitops-demo/nginx:$(date +%s)     
